CREATE TABLE races (
  id TEXT PRIMARY KEY
);

CREATE TABLE results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  race_id TEXT NOT NULL,
  name TEXT NOT NULL,
  time TEXT NOT NULL,
  FOREIGN KEY (race_id) REFERENCES races(id)
);
